baseURL = 'https://NickWarshak.github.io/my-portfolio/'
languageCode = 'en-us'
title = 'Nick Warshak'
theme = "PaperMod"
[params]
    # General Site Settings
    assets = { disableFingerprinting = false }
    env = "production"
    mainSections = ["projects"] # Tells Hugo to only show Projects on the home feed

    [params.homeInfoParams]
        Title = "Personal Website & Portfolio"
        Content = """
    Welcome to my digital portfolio! 
    
    I'm a developer and analyst focused on building data-driven insights
    and solutions. Explore the **Projects** tab to see what i've been 
    working on check out my **Coursework** for academic highlights, 
    or head over to the **Personal** page to see what I'm up to 
    when my laptop is closed.
    """
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/nicholas-warshak"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/NickWarshak"

    [[params.socialIcons]]
        name = "cv" 
        url = "/Nick_Warshak_Resume.pdf"
        title = "Resume PDF"

# Navigation Menu
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10

[[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 20

[[menu.main]]
    name = "Coursework"
    url = "/coursework/"
    weight = 30

[[menu.main]]
    name = "Personal"
    url = "/personal/"
    weight = 40