baseURL = 'https://NickWarshak.github.io/my-portfolio/'
languageCode = 'en-us'
title = 'Nick Warshak'
theme = "PaperMod"
[params]
    # This tells the theme to bundle your custom CSS
    assets = { disableFingerprinting = false }
    env = "production" # Moved this up here

    [params.homeInfoParams]
        Title = "Personal Website & Portfolio"
        Content = "Information Systems student at the University of Cincinnati with a certification in Computer Science. Focused on leveraging critical thinking, hard skills, and AI to solve complex problems."

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/nicholas-warshak"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/NickWarshak"
    [[params.socialIcons]]
        name = "cv" # This will usually show a paper/document icon
        url = "Nick_Warshak_Resume.pdf"
        title = "Resume PDF"
    [params]
        mainSections = ["projects"]
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10  # Lowest weight = First on the left

[[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 20

[[menu.main]]
    name = "Coursework"
    url = "/coursework/"
    weight = 30
[[menu.main]]
    name = "Personal"
    url = "/personal/"
    weight = 40