baseURL = 'https://NickWarshak.github.io/my-portfolio/'
languageCode = 'en-us'
title = 'Nick Warshak'
theme = "PaperMod"
[params]
    # This tells the theme to bundle your custom CSS
    assets = { disableFingerprinting = false }
[params.homeInfoParams]
    Title = "Personal Website & Portfolio"
    Content = "Information Systems student at the University of Cincinnati. Aspiring Data Scientist & AI enthusiast."

[[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/nicholas-warshak"
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/NickWarshak"
[[menu.main]]
    name = "Experience"
    url = "/experience"
    weight = 10
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 20
[[menu.main]]
    name = "Coursework"
    url = "/coursework"
    weight = 30