baseURL = 'https://NickWarshak.github.io/my-portfolio/'
languageCode = 'en-us'
title = 'Nick Warshak'
theme = "PaperMod"
[params]
    # General Site Settings
    assets = { disableFingerprinting = false }
    env = "production"
    mainSections = ["projects"] # Tells Hugo to only show Projects on the home feed

    [params.homeInfoParams]
        Title = "Personal Website & Portfolio"
        Content = "Information Systems student at the University of Cincinnati with a certification in Computer Science. Focused on leveraging critical thinking, hard skills, and AI to solve complex problems. Please visit the tabs in the top right to see some of my projects, experience, coursework, and even a personal page."

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/nicholas-warshak"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/NickWarshak"

    [[params.socialIcons]]
        name = "cv" 
        url = "/Nick_Warshak_Resume.pdf"
        title = "Resume PDF"

# Navigation Menu
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10

[[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 20

[[menu.main]]
    name = "Coursework"
    url = "/coursework/"
    weight = 30

[[menu.main]]
    name = "Personal"
    url = "/personal/"
    weight = 40